apiVersion: v1
kind: Secret
metadata:
  name: fitrack-secrets
  namespace: fitrack
type: Opaque
stringData:
  IAM_DB_USER: "iam_user"
  IAM_DB_PASSWORD: "iam_password"
  IAM_DB_NAME: "iam_db"

  WORKOUT_DB_USER: "workout_user"
  WORKOUT_DB_PASSWORD: "workout_password"
  WORKOUT_DB_NAME: "workout_db"

  JWT_SECRET: "supersecretkeysupersecretkey123456"
