apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fitrack-ingress
  namespace: fitrack
spec:
  rules:
    - host: iam.fitrack.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: iam
                port:
                  number: 8080
    - host: workout.fitrack.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: workout
                port:
                  number: 8080
